### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by Sakatland** [tonybenoy/cocapi#18]
Small detail but in Readme.md it is written "api.clan_warleague(war_tag)" for Warleague Information and in the cocapi.py there is no "clan_" in the function.

**Comment by tonybenoy** [comment]
Thanks for reporting this. I've fixed it in https://github.com/tonybenoy/cocapi/commit/76eed7577b8da319575155ec48f8f69a0597780f . Close the issue once confirmed.
