### ISSUE TITLE
New endpoints

### ISSUE THREAD

**Issue by Sakatland** [tonybenoy/cocapi#29]
Last update changed and added new endpoints, do you plan to add it?

*****

The next Clash of Clans release will introduce the following changes in the API of the game.

Some existing routes and model properties will become deprecated: they will still be present in the API for now but eventually they will be removed.

There will not be a replacement in the API for the versusBattleWins property. After the next Clash of Clans release this property will be constant zero until it will eventually be removed.

Routes

    The route /locations/{locationId}/rankings/clans-versus will become deprecated and replaced by the route /locations/{locationId}/rankings/clans-builder-base.
    The route /locations/{locationId}/rankings/players-versus will become deprecated and replaced by the route /locations/{locationId}/rankings/players-builder-base.
    The routes /builderbaseleagues and /builderbaseleagues/{leagueId} will be added.

Models
Clan

    The property clanVersusPoints will become deprecated and replaced by the property clanBuilderBasePoints.
    The property requiredVersusTrophies will become deprecated and replaced by the property requiredBuilderBaseTrophies.

ClanMember

    The property versusTrophies will become deprecated and replaced by the property builderBaseTrophies.
    The property builderBaseLeague will be added.

ClanVersusRanking

    This model will be renamed to ClanBuilderBaseRanking.
    The property clanVersusPoints will become deprecated and replaced by the property clanBuilderBasePoints.

Player

    The property versusTrophies will become deprecated and replaced by the property builderBaseTrophies.
    The property versusBattleWins will become deprecated and will be constant zero until it is removed.
    The property legendStatistics.previousVersusSeason will become deprecated and replaced by the property legendStatistics.previousBuilderBaseSeason.
    The property legendStatistics.bestVersusSeason will become deprecated and replaced by the property legendStatistics.bestBuilderBaseSeason.
    The property builderBaseLeague will be added. It will be present only if Builder Base has been unlocked, similar to e.g. the property builderBaseTrophies.

PlayerVersusRanking

    This model will be renamed to PlayerBuilderBaseRanking.
    The property versusTrophies will become deprecated and replaced by the property builderBaseTrophies.
    The property versusBattleWins will become deprecated and will be constant zero until it is removed.
    The property builderBaseLeague will be added._

*****

Source:
https://discord.com/channels/566451504332931073/854485301748432907/1106542015023419452

**Comment by tonybenoy** [comment]
Hey @Sakatland. For some reason I never got notified of the issue! But anyways it's been a while since I played COC 😅. I'll add them in a few days once I get some free time. Sorry for the delay. If it's something  that someone can pickup I'd be happy to share the load.

**Comment by tonybenoy** [comment]
#30

**Comment by tonybenoy** [comment]
@Sakatland I've added the new endpoints(except verify token) and also added deprecation warnings for the to be deprecated APIs. I currently don't have the bandwidth to to a full test. Would it be possible for you to maybe take the branch for a test spin?

**Comment by Sakatland** [comment]
Hey thanks @tonybenoy
I just runned a test quickly, it seems to work. Altough I couldn't test further as I'm away.

**Comment by tonybenoy** [comment]
Awesome. I've added it as a pre release so that I can test it a bit more. Once I'm done I'll make a pypy release.
